### ISSUE TITLE
Add tag jdk-22 for Setup-GraalVM to find.

### ISSUE THREAD

**Issue by thejudge156** [bell-sw/LibericaNIK#24]
Currently there is no JDK22 tags, and it breaks the [GraalVM Setup Action](https://github.com/graalvm/setup-graalvm/tree/main). It checks for a branch starting with jdk-{javaVersion}, an additional 22 tag would be appreciated.

**Comment by petermz** [comment]
Thanks for noticing! Published https://github.com/bell-sw/LibericaNIK/releases/tag/jdk-22.0.1%2B10

**Comment by thejudge156** [comment]
Thanks! That fixed it.
