### ISSUE TITLE
Can we release the latest version that supports JDK 17

### ISSUE THREAD

**Issue by imgoby** [bell-sw/LibericaNIK#26]
Can we release the latest version that supports JDK 17.
For Example: graalvm 23.1.5.0 + JDK 17

**Comment by voitylov** [comment]
the latest version with JDK 17 support is 23.0.5, which is available
- on website: https://bell-sw.com/pages/downloads/native-image-kit/#nik-23-(jdk-17)
- in github releases https://github.com/bell-sw/LibericaNIK/releases/tag/23.0.5%2B1-17.0.12%2B10

**Comment by imgoby** [comment]
thank you.
but,graalvm 23.1.5.0 is not yet.Graalvm 23.1.5.0 seems to have a bug that I am looking forward to fixing.

**Comment by voitylov** [comment]
23.1.x branch is based on JDK 21. 23.0.x branch is based on JDK 17. There are no plans to release 23.1.x based on JDK 17.

**Comment by imgoby** [comment]
OK, Thank you. I update to  the newer version.
